In [97]:
import numpy as np
import pandas as pd
import math as mt

In [99]:
mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

In [101]:
mat_array = np.array(mat)

In [103]:
mat_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [105]:
mat_array.shape

(3, 5)

In [107]:
mat_array[0,:]

array([0, 1, 2, 3, 4])

In [109]:
mat_array[-2,:]

array([5, 6, 7, 8, 9])

In [111]:
mat_array[1,2]

7

.sin() .cos() .factorial()

In [114]:
print("SIN di 90", mt.sin(mt.pi/2), "COS di 90", mt.cos(mt.pi/2), "SIN di 180", mt.sin(mt.pi), "COS di 180", mt.cos(mt.pi))

SIN di 90 1.0 COS di 90 6.123233995736766e-17 SIN di 180 1.2246467991473532e-16 COS di 180 -1.0


In [122]:
print(mt.factorial(9))

362880


In [124]:
mt.degrees(mt.pi)

180.0

In [126]:
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]

In [128]:
lst = np.array(lst)
lst

array([2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100,
       5350])

qual è stata la vendita massima mensile? e quella minima? e quella media?

In [131]:
print(lst.max())
print(lst.min())

8150
1280


quali sono le vendite mensili maggiori di 4999 oggetti? E quante ne sono?

In [134]:
filter_4999 = lst[lst > 4999]
print(filter_4999)
print(len(filter_4999))

[5500 7200 6410 8150 7100 5350]
6


quali sono le vendite minori di 3000 oggetti?

In [137]:
filter_3000 = lst[lst < 3000]
print(filter_3000)
print(len(filter_3000))

[2000 1280 1900 2500]
4


in media quanti oggetti sono stati venduti al mese? e poi arrotondiamo

In [140]:
print(round(lst.mean(), 2))

4634.17


In [142]:
#dizionario
fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 2003: 14_000, 2004: 21_000}
#serie pandas, a differenza dei dizionari con le serie possiamo fare operazioni
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000], index=range(1997, 2005))

In [144]:
fatturati_dict[1997] 

12000

In [146]:
fatturati_series[1997]

12000

In [148]:
stipendi = np.array( [100, 200, 300, 400, 500,  600, 700, 800, 900, 1000] )

L'azienda ci chiede di raddoppiare tutti gli stipendi; facciamolo in due modi: 

In [151]:
print(stipendi)

[ 100  200  300  400  500  600  700  800  900 1000]


In [153]:
lista_stipendi_raddoppiati = []
lista_stipendi_raddoppiati_com = []
#ciclo for
for stipendio in stipendi:
    lista_stipendi_raddoppiati.append(stipendio * 2)
print("lista stipendi raddoppiati for: ", lista_stipendi_raddoppiati)
#list comprehension
lista_stipendi_raddoppiati_com = [stipendio * 2 for stipendio in stipendi]
print("lista stipendi raddoppiati comp: ", lista_stipendi_raddoppiati_com)
#masking
lista_stipendi_raddoppiati_numpy = stipendi*2
print("lista stipendi raddoppiati mask: ", lista_stipendi_raddoppiati_numpy)

lista stipendi raddoppiati for:  [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]
lista stipendi raddoppiati comp:  [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]
lista stipendi raddoppiati mask:  [ 200  400  600  800 1000 1200 1400 1600 1800 2000]


In [156]:
#ciclo for in range
for x in range(100, 110):
    print(x)

100
101
102
103
104
105
106
107
108
109


In [159]:
for x in range(0, 100, 10):
    print(x)

0
10
20
30
40
50
60
70
80
90


In [162]:
for x in range(0, len(lst)):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [164]:
libri = ["enciclopedia", "atlante", "dizionario"] 
for libro in libri: 
    print(libro) 
for contatore, libro in enumerate(libri): 
    print(contatore, libro)

enciclopedia
atlante
dizionario
0 enciclopedia
1 atlante
2 dizionario


In [170]:
nomi = ['Anna', 'Bruno', 'Carla']
età = [28, 34, 29]

persone = zip(nomi, età)
# Converti l'iteratore in una lista di tuple
lista_persone = list(persone)
print(lista_persone)

for nome, età in zip(nomi, età):
    print(f"{nome} ha {età} anni.")

[('Anna', 28), ('Bruno', 34), ('Carla', 29)]
Anna ha 28 anni.
Bruno ha 34 anni.
Carla ha 29 anni.
